### ISSUE TITLE
Glib-2.66 Builds but cannot install

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/BMLFS#15]
Glib build fine with meson and samurai, but will not install:
```
Installing docs/reference/gio/gapplication.1 to /BUILD/usr/share/man/man1
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 134, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 719, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 511, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 673, in install_targets
    self.fix_rpath(outname, t.rpath_dirs_to_remove, install_rpath, final_path,
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 325, in fix_rpath
    depfixer.fix_rpath(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/depfixer.py", line 509, in fix_rpath
    fix_darwin(fname, new_rpath, final_path, install_name_mappings)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/depfixer.py", line 421, in fix_darwin
    rpaths = get_darwin_rpaths_to_remove(fname)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/depfixer.py", line 402, in get_darwin_rpaths_to_remove
    out = subprocess.check_output(['otool', '-l', fname],
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'otool'
samu: job failed: /usr/bin/meson install --no-rebuild
samu: subcommand failed
```
Host: CMLFS 2.0.0

**Comment by dslm4515** [comment]
Same error with glib-2.68.3.

Install completes with out error if i create a dummy link:
```
ln -sv true /bin/otool
```

**Comment by dslm4515** [comment]
No longer using glib-2.66... already upgraded to 2.7x
