### ISSUE TITLE
Blueman Fails to Launch in Wayland

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/BMLFS#24]
Blueman will crash when launched from a wayland session:

```
$ blueman-applet 
blueman-applet 14.58.35 ERROR    PluginManager:90 load_plugin: Unable to load plugin module GameControllerWakelock
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/main/PluginManager.py", line 88, in load_plugin
    importlib.import_module(self.module_path.__name__ + f".{plugin}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/blueman/plugins/applet/GameControllerWakelock.py", line 15, in <module>
    raise ImportError('This is not an X11 screen')
ImportError: This is not an X11 screen
blueman-applet 14.58.35 WARNING  PluginManager:147 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 14.58.35 WARNING  TransferService:213 _make_share_path: Failed to get Download dir from XDG
blueman-applet 14.58.35 WARNING  PluginManager:147 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 14.58.36 WARNING  DiscvManager:119 update_menuitems: warning: Adapter is None
Segmentation fault
```

Looks like hardcoded for X11

**Comment by thefoster** [comment]
Same here on Kubuntu 22.04 with Plasma 5.25.5.
Blueman-manager segfaults under Wayland.
Unfortunately blueman is so far the only way i could find to connect a serial port to my GPS device (V900), which the common bluetooth stack cannot handle at all.

$ strace blueman-manager
[...]
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7ffc453d9ff8} ---
+++ killed by SIGSEGV (core dumped) +++
